spring:
  datasource:
    url: jdbc:h2:file:./camunda-h2-database
  cloud:
    function:
      definition: transacaoConsumer
    stream:
      bindings:
        transacaoConsumer-in-0:
          destination: transacao
          group: transacao-service
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092



camunda.bpm.admin-user:
  id: demo
  password: demo