server:
  port: 8083
spring:
  datasource:
    url: jdbc:h2:file:./camunda-h2-database
  cloud:
    function:
      definition: transacaoConsumer
    stream:
      bindings:
        transacaoConsumer-in-0:
          destination: transacao-topic
          group: transacao-service
          content-type: application/json
        transacaoProducer-out-0:
          destination: transacao-topic
        notificacaoProducer-out-0:
          destination: notificacao-topic
        registroTransacaoProducer-out-0:
          destination: registro-transacao-topic
      kafka:
        binder:
          brokers: localhost:9092



camunda.bpm.admin-user:
  id: demo
  password: demo